---
title: "ESM 270 Assignment 8 - R Hot Spots"
author: "Laura Ingulsrud & Tess Hooper"
date: "5/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, Load Packages, echo = FALSE}

library(tidyverse)

# Load the libraries into this R session
library(raster)       #Main raster library with nearly all functions used in this analysis
library(rgdal)        #Spatial library - most functions used from rgdal are for vectors (shapefiles)
library(rasterVis)    #Useful for raster visualizations
library(maps)         #Has a database of maps. I use this to add a map to my raster to visualize land boundaries
library(rgeos)        #Need this library for topology operations on geometries
library(dplyr)        #NOT spatial - this is a data wrangling library
library(RColorBrewer) #Also not spatial - used to set the spectral color scheme
library(tmap)

```

```{r, Part 2}

# view some color palettes
# display.brewer.all()
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))

```

```{r, Read in Threat Raster Data}

# Let’s import the raster with the cumulative threat layer. Create a raster of the first file by calling raster() (think of this function like read.csv() for raster data, if you are familiar with that function).

# Read in raster data
impact_invasives <- raster("impact_invasives.tif")
impact_oil <- raster("impact_oil.tif")
impact_pens <- raster("impact_pens.tif")
impact_pollution <- raster("impact_pollution.tif")
impact_shipping <- raster("impact_shipping.tif")
impact_trash <- raster("impact_trash.tif")

```

```{r, Vizualize Threats}

# We can then use plot() to plot the raster; it’s that easy! To override the default color scheme, we define the argument col= as our own scheme cols from above.

plot(impact_invasives,col=cols)
plot(impact_oil,col=cols)
plot(impact_pens,col=cols)
plot(impact_pollution,col=cols)
plot(impact_shipping,col=cols)
plot(impact_trash,col=cols)

# We can add a basemap to our raster by utilizing the maps package

# add a landmap to your shapefile. the add=T argument tells R to add it to the existing plot.
# make sure you understand what the other arguments do
plot(impact_invasives,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')

plot(impact_oil,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')

plot(impact_pens,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')

plot(impact_pollution,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')

plot(impact_shipping,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')

plot(impact_trash,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')


```

```{r, Extent and Zoom}

# Visualizing exploring rasters in different ways can give us a great idea of our data, without even running much analysis. You can visualize a different extent, or subset, of the data:

plot(impact_trash,col=cols,ext=extent(-121,-117,32,35),main="Ocean Pollution Threats") # A good extent for the Santa Barbara Channel

# Lower values are in darker/cooler colors; higher threat values are in red colors (scale of 0 to 65)
  # it's actually the stack of these threats; each # in the stack adds together to get this stacked score

# The zoom() function, by default, allows you to draw your own extent just by clicking twice.
plot(impact_trash,col=cols)
# zoom(all_threats,col=cols) #Interactive code not run in html

# QUESTION: Which part of the SF Bay area is at highest threat?
  # Areas right along the shore, up into the estuary. If we included runoff, pollution, or coastal erosion, that might make sense that some of the highest threat values in the bay area are right near the city.

```

```{r, Threat Raster data attributes}

# Beyond visualization, we can also look at some simple characteristics of the data itself. Just calling the name of our raster will give us some information:

impact_invasives 
impact_oil 
impact_pens 
impact_pollution 
impact_shipping
impact_trash 

# QUESTION: What is the minimum value of all raster cells in our threats layer?


# We can look at the frequency histogram of raster cell values.
hist(impact_invasives,main="Invasives Threats Frequency")
# warning message: it knew we were stupid to choose 16 million to do a histogram on, so it chose a subset for us
# frequency in this case, the number of cells, that fall within one bin (bins of 5)

# Also, the function cellStats() allows us to run some basic statistics. Type ?cellStats to read what the function can do
  # stat is the function we want it to run

# We want to get the mean of the all_threats raster
cellStats(impact_invasives,mean)
# [1] -5.001484e+33

# QUESTION: What is the standard deviation of all raster cells in our threats layer?
cellStats(impact_invasives,sd)
# 2.235841e+35
# Seems to have a pretty tight distribution with these long tails

```

```{r, Part 3: Raster Calculations}

# Quickly visualizing raster data in R is nice, but the real power of raster analysis is when we can perform calculations that link two or more raster layers. If you remember from our hotspots lab, our first task was to overlay the top 20% of cumulative threats with the top 20% of species richness, to find threat hotspots (where high species richness overlaps with a lot of different threats). This will require 4 steps:

# 1) Import the data (already done for threats)
# 2) Resample the data to the same resolution
# 3) Reclassify the data to find the top 20%
# 4) Overlay the data and find hotspots

```

```{r, Import Species Data}

# The species data is in the Species data directory, and we import it just as we did the threats layer, by providing a full path name. We can then check its attributes.

# Make sure the pathname to the data is correct
krill_1 <- raster("ca_current_aquamap_Euphausia_diomedeae.tif")
krill_2 <- raster("ca_current_aquamap_Euphausia_gibboides.tif")
krill_3 <- raster("ca_current_aquamap_Euphausia_pacifica.tif")
krill_4 <- raster("ca_current_aquamap_Euphausia_tenera.tif")

krill_1
krill_2
krill_3
krill_4

plot(krill_1,col=cols)


blue_whale <- raster("ca_current_aquamap_Balaenoptera_musculus.tif")
fin_whale <- raster("ca_current_aquamap_Balaenoptera_physalus.tif")
humpback <- raster("ca_current_aquamap_Megaptera_novaeangliae.tif")

# Seem to be more species toward the coast than offshore

```

```{r, Cropping and Resampling}

# If you type all_spp and all_threats (or plot them), you should be able to tell that we may run into problems trying to immediately do calculations on them, as they have different extents and resolutions. Two helpful functions to deal with these problems are crop() and resample().

# QUESTION: Before doing the next step, which of our two rasters has a greater extent? a higher (finer) resolution? What does this mean about how we should resample?
  # The threats layer raster has a greater extent. (compare the "extent" when you type "all_threats" and "all_spp" into console or code)
  # The threats layer raster has a higher (finer) resolution.
  # We should resample using the threats layer

########################################################################################
#### CROP #####
# We first crop the threats layer to the extent of the species layer

#?crop see what the crop function does

invasives_crop <- crop(impact_invasives, krill_1) #Crop the threats layer to the same extent at species
oil_crop <- crop(impact_oil, krill_1)
pens_crop <- crop(impact_pens, krill_1)
pollution_crop <- crop(impact_pollution, krill_1)
shipping_crop <- crop(impact_pollution, krill_1)
trash_crop <- crop(impact_trash, krill_1)

#######################################################################################

#### RESAMPLE ####
# Now the threats layer has the same extent as the species layer. But we have to resample the species layer such that it has the same resolution as the threats layer.



#?resample see what the resample function does
# NOTE: the progress='text' argument is a great tool: it prints out the progress
# of a longer-running function into the console, so you can see how the operation is going



# the method='ngb' argument specifies that we want to use a nearest neighbor algorithm to resample, instead of interpolation


krill1_res <- resample(krill_1,invasives_crop,method='ngb',progress='text')
krill2_res <- resample(krill_2,invasives_crop,method='ngb',progress='text')
krill3_res <- resample(krill_3,invasives_crop,method='ngb',progress='text')
krill4_res <- resample(krill_4,invasives_crop,method='ngb',progress='text')

blue_res <- resample(blue_whale,invasives_crop,method='ngb',progress='text')
fin_res <- resample(fin_whale,invasives_crop,method='ngb',progress='text')
humpback_res <- resample(humpback,invasives_crop,method='ngb',progress='text')


# Have to think about which way we want to go for our own analysis
# We're subsetting the species raster so it has a higher resolution
# "ngb" = nearest neighbor; this cell will take the value of the closest cell 


```



```{r, Raster Stack Threats and Species}

#### RASTER STACK ####
# We can check that the two layers will line up decently by using the stack() function. stack() creates a RasterStack object, which is basically just exactly what it sounds like: A single object holding multiple raster layers. This isn’t as useful for just a couple of layers, but it will likely be useful to you later on when you are combining multiple threat layers.

# stack: putting the layers on top of each other and seeing if they line up
# if they don't line up, it won't stack (error)

krill1_invasives_stack <- stack(invasives_crop,krill1_res)
plot(krill1_invasives_stack,col=cols)

# Even though these layers still look similar to how they did before, the fact that they stacked together means they are likely ready for combination.

# Even though it looks big and blocky, it has a lot of smaller cells in there
# bilinear: if I'm at 1 and looking up at 3, the values between me and there are going to be up along that slope, as opposed to (1 1 1 1 1, break, 3 3 3 3 3); it's just the slope of the line between the two cells

#### RECLASSIFY ####
hist(spp_res,main="Species Raster Values")

# notice that in the following, we are OVERWRITING the original spp_res object.
# This is okay in this instance since we won't be using the old version, but
# often it is better to assign any output of a function to a new variable or object
spp_res <- reclassify(spp_res,rcl=c(-Inf,0,NA)) 
  # "-Inf" is anything lower than or equal to 0
hist(spp_res,main="Species Raster Values, Zeroes Removed") # did the function do what we were hoping?
plot(spp_res)

#?quantile what does the quantile function do?
spp_cutoff <- quantile(spp_res,0.8) # Find the value of the 80th percentile
  # 700
spp_maxVal <- cellStats(spp_res,max) #find the maximum
  # 3099

# Our reclassification matrix. Make sure you know what this is saying
rcl_mat <- c(-Inf,spp_cutoff,0,
            spp_cutoff,spp_maxVal,1)
  # anywhere from less than 0 down to this cutoff value, that will be 0
  # anywhere from the cutoff value to the maximum value, we want that to be 1

# Reclassify the species layer
spp_binary <- reclassify(spp_res,rcl=rcl_mat)

# Because we have binary data now, I want to change the color scheme again
binary_cols <- c("white","firebrick")
plot(spp_binary,col=binary_cols,legend=F,main="Top 20% of Species Richness")
map('world',fill=T,add=T,col='gray')

# TASK: Reclassify the threats layer (make sure it is the one with the correct extent!) to assign a value of 1 to the top 20% of the cells, and a zero to the others

hist(threats_crop,main="Threat Raster Values")

#?quantile what does the quantile function do?
threat_cutoff <- quantile(threats_crop,0.8) # Find the value of the 80th percentile
  # 16.1
threat_maxVal <- cellStats(threats_crop,max) #find the maximum
  # 83.846

# Our reclassification matrix. Make sure you know what this is saying
rcl_mat_threat <- c(-Inf,threat_cutoff,0,
            threat_cutoff,threat_maxVal,1)

# Reclassify the species layer
threat_binary <- reclassify(threats_crop,rcl=rcl_mat_threat)

# Because we have binary data now, I want to change the color scheme again
binary_cols_threat <- c("white","firebrick")
plot(threat_binary,col=binary_cols_threat,legend=F,main="Top 20% of Threats")
map('world',fill=T,add=T,col='gray')



```


```{r, Hotspots}


#### HOTSPOTS ####

# the hotspots
hotspots <- overlay(spp_binary,threat_binary,fun=function(x,y){x+y})

# color breakpoints. We need three colors now! (cell values of 0,1,or 2)
brks_hotspots <- seq(0,3,length.out=4) 
hotspot_cols <- c("white","lightblue","firebrick") #

# plot the hotspots!
plot(hotspots,col=hotspot_cols,legend=F,main="Hotspots");map('world',fill=T,add=T,col='gray80')

plot(hotspots,col=hotspot_cols,ext=extent(-121,-117,32,35),main="Hotspots, SB Channel",legend=F)
map('world',fill=T,add=T,col='gray80')


```



```{r, Shortcut for Overlaying}


#### Reclassify ####

# Reclassify the 0's to NA values. we want to find the top 20% of cells in each layer, and then combine the two layers to produce hotspots.

krill_1 <- reclassify(krill_1,rcl=c(-Inf,0,NA)) # reclass 0 to NA
krill_2 <- reclassify(krill_2,rcl=c(-Inf,0,NA)) 
krill_3 <- reclassify(krill_4,rcl=c(-Inf,0,NA)) 
krill_4 <- reclassify(krill_4,rcl=c(-Inf,0,NA)) 

blue_whale <- reclassify(blue_whale,rcl=c(-Inf,0,NA)) 
fin_whale <- reclassify(fin_whale,rcl=c(-Inf,0,NA)) 
humpback <- reclassify(humpback,rcl=c(-Inf,0,NA)) 

#### Crop ####

# Crop each threat layer to Krill_1 Species so that they are the same extent (All species layers are already in the same extent)

invasives_crop <- crop(impact_invasives, krill_1) #Crop the threats layer to the same extent at species
oil_crop <- crop(impact_oil, krill_1)
pens_crop <- crop(impact_pens, krill_1)
pollution_crop <- crop(impact_pollution, krill_1)
shipping_crop <- crop(impact_pollution, krill_1)
trash_crop <- crop(impact_trash, krill_1)




#### Resample ####

# Resample each species layer to the threat resolution (Threat layers have the higher resolution)

krill1_res <- resample(krill_1,invasives_crop,method='ngb',progress='text')
krill2_res <- resample(krill_2,invasives_crop,method='ngb',progress='text')
krill3_res <- resample(krill_3,invasives_crop,method='ngb',progress='text')
krill4_res <- resample(krill_4,invasives_crop,method='ngb',progress='text')

blue_res <- resample(blue_whale,invasives_crop,method='ngb',progress='text')
fin_res <- resample(fin_whale,invasives_crop,method='ngb',progress='text')
humpback_res <- resample(humpback,invasives_crop,method='ngb',progress='text')





#### Function to output a binary raster based on a user-given quantile (default is top 20%) ###

reclassify_topx <- function(rast,quant=0.8) {
  topx <- quantile(rast,quant) #find the 80% quantile of the raster values
  maxVal <- cellStats(rast,max) #find the maximum
  rcl <- c(-Inf,topx,0,
            topx,maxVal,1) # reclassify matrix (see help file for ?reclassify)
  out <- reclassify(rast,rcl=rcl)
  return(out) # returns the new binary raster
}




### Find top 20% of Threats, using the code from above. We could easily choose a different quantile here. ###
invasives_top20 <- reclassify_topx(invasives_crop,quant=0.8)
oil_top20 <- reclassify_topx(oil_crop,quant=0.8)
pens_top20 <- reclassify_topx(pens_crop,quant=0.8)
pollution_top20 <- reclassify_topx(pollution_crop,quant=0.8)
shipping_top20 <- reclassify_topx(shipping_crop,quant=0.8)
trash_top20 <- reclassify_topx(trash_crop,quant=0.8)


### Find top 20% of Species
krill1_top20 <- reclassify_topx(krill1_res,quant=0.8)
krill2_top20 <- reclassify_topx(krill2_res,quant=0.8)
krill3_top20 <- reclassify_topx(krill3_res,quant=0.8)
krill4_top20 <- reclassify_topx(krill4_res,quant=0.8)

blue_top20 <- reclassify_topx(blue_res,quant=0.8)
fin_top20 <- reclassify_topx(fin_res,quant=0.8)
humpback_top20 <- reclassify_topx(humpback_res,quant=0.8)





### overlay and plot the hotspots ###

# Overlay all Threats to get One Raster

threat_hotspots <- overlay(invasives_top20, oil_top20, pens_top20, pollution_top20, shipping_top20, trash_top20, fun=function(a,b,c,d,e,f){a+b+c+d+e+f})

plot(threat_hotspots)

# Green is where there are 4 threats present. Not all 6 threats are together at once in any spot. The most is 4 threats. It doesn't specify which threats they are. 


# Overlay all Species to get One Raster 
species_hotspots <- overlay(krill1_top20, krill2_top20, krill3_top20, krill4_top20, blue_top20, fin_top20, humpback_top20,  fun=function(a,b,c,d,e,f,g){a+b+c+d+e+f+g})

plot(species_hotspots)




# Overlay Species and Threats


hotspots <- overlay(threat_hotspots,species_hotspots,fun=function(x,y){x*y})

plot(hotspots)




#### Plot the Hotspots  ####
 

# plot the hotspots!
plot(hotspots,legend=F,main="Hotspots");map('world',fill=T,add=T,col='gray80')

```
